url: "https://itseunsoo.github.io/KivaBrand" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Kiva Studio" # the name of your site, e.g. ACME Corp.